FROM mcr.microsoft.com/windows/servercore:ltsc2022 as core


FROM plugins/base:windows-ltsc2022-amd64
USER ContainerAdministrator

ENV GODEBUG=netdns=go
COPY --from=core /windows/system32/netapi32.dll /windows/system32/netapi32.dll

ADD release/windows/amd64/plugin.exe C:/plugin.exe
ENTRYPOINT [ "C:\\plugin.exe" ]